### ISSUE TITLE
.HLSL support for simple use with MPC-HC

### ISSUE THREAD

**Issue by HUNGDUNG7805** [MaxG2D/ReshadeSimpleHDRShaders#1]
I recently tried your shader pack (HDR_Saturation), it works best for me and I want to have it installed with SVP to watch Anime on MPC-HC. However, the SVP version (3.17) seems to not supported by any kind of ReShade version I downloaded. I wonder if you can publish a .HLSL - adapted version of this shader to be used with ease, or please guide me on how can I create a similar HLSL shader code for my self. I would be very appreciated.

**Comment by MaxG2D** [comment]
Hi!

Happy to see that you like my shaders. That being said, I'm not really interested in porting it to any other platform, but ReShade pseudo HLSL syntax is fairly similar to regular HLSL, so I can refer you to official ReShade documentation: [ReShade Reference](https://github.com/crosire/reshade-shaders/blob/slim/REFERENCE.md)

**Comment by HUNGDUNG7805** [comment]
> Hi!
> 
> Happy to see that you like my shaders. That being said, I'm not really interested in porting it to any other platform, but ReShade pseudo HLSL syntax is fairly similar to regular HLSL, so I can refer you to official ReShade documentation: [ReShade Reference](https://github.com/crosire/reshade-shaders/blob/slim/REFERENCE.md)

Well, at last I got it worked with a cracked version of SVP, guess ill just use ReShade for now, despite the fact that the welcome message and loading time of shaders disturb me a little bit. Thanks anyway for the dedicated shader code. It reassemble pretty much the color intensity (which looks really good on animes) that I used to get on my iGPU (HD 620) DXVA2 engine xD

**Comment by HUNGDUNG7805** [comment]
> Hi!
> 
> Happy to see that you like my shaders. That being said, I'm not really interested in porting it to any other platform, but ReShade pseudo HLSL syntax is fairly similar to regular HLSL, so I can refer you to official ReShade documentation: [ReShade Reference](https://github.com/crosire/reshade-shaders/blob/slim/REFERENCE.md)

Oh BTW does this work with older version of ReShade? (4.9.1.0 in particular), I downloaded a modded version of ReShade 4.9.1.0 which disable the welcome message, but it seems that this shader failed to load

**Comment by MaxG2D** [comment]
> > Hi!
> > Happy to see that you like my shaders. That being said, I'm not really interested in porting it to any other platform, but ReShade pseudo HLSL syntax is fairly similar to regular HLSL, so I can refer you to official ReShade documentation: [ReShade Reference](https://github.com/crosire/reshade-shaders/blob/slim/REFERENCE.md)
> 
> Oh BTW does this work with older version of ReShade? (4.9.1.0 in particular), I downloaded a modded version of ReShade 4.9.1.0 which disable the welcome message, but it seems that this shader failed to load

Show me the error message, no idea what I should fix if I don't see what's broken

**Comment by HUNGDUNG7805** [comment]
> > > Hi!
> > > Happy to see that you like my shaders. That being said, I'm not really interested in porting it to any other platform, but ReShade pseudo HLSL syntax is fairly similar to regular HLSL, so I can refer you to official ReShade documentation: [ReShade Reference](https://github.com/crosire/reshade-shaders/blob/slim/REFERENCE.md)
> > 
> > 
> > Oh BTW does this work with older version of ReShade? (4.9.1.0 in particular), I downloaded a modded version of ReShade 4.9.1.0 which disable the welcome message, but it seems that this shader failed to load
> 
> Show me the error message, no idea what I should fix if I don't see what's broken

Oh nvm, its just an easy fix for me :v
The reason why the shader failed to load is because older versions of ReShade (or at least my version) did not automatically install the ReShade.fxh/ ReShadeUI.fxh package, which i saw included to be load in your shader code. Just install the lastest ReShade > copy bot ReShade.fxh package > uninstall + install the modded version > paste both ReShade.fxh package in the "effect directory", and the shader (HDR-Saturation in my case) will load normally
